version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    rebase-strategy: auto
    ignore:
      - dependency-name: "org.springframework.boot"
        versions: ["5.x"]
    allow:
      - dependency-type: "direct"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
