version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    rebase-strategy: auto
    ignore:
      # Ignorar actualizaciones conflictivas o que ya maneja el BOM de Spring Boot y Cloud
      - dependency-name: "org.springframework.boot*"
      - dependency-name: "org.springframework.security*"
      - dependency-name: "org.springframework.cloud*"
      - dependency-name: "org.springframework*"
      - dependency-name: "io.netty*"
      - dependency-name: "net.minidev*"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
