spring:
  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://prod-db.example.com:5432/prod_db}
    username: ${DB_USERNAME:prod_user}
    password: ${DB_PASSWORD:prod_pass}
    pool:
      enabled: true
      initial-size: 20
      max-size: 50
      max-idle-time: 30m

  kafka:
    bootstrap-servers: kafka.prod.example.com:9092
    consumer:
      group-id: template-service-prod
    producer:
      retries: 15

logging:
  level:
    root: ERROR
    com.company.templateservice: WARN
