name: Dependency Check

on:
  schedule:
    - cron: '0 0 * * 1'  # Ejecutar semanalmente los lunes
  workflow_dispatch:

jobs:
  check-dependencies:
    name: Dependency Update Report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Check dependency updates
        run: ./gradlew dependencyUpdates -Drevision=release
