name: Dependency Check Badge Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'  # Every Monday at 12:00 UTC

jobs:
  dependency-check:
    name: Update Dependency Badge in Gist
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Check dependency updates
        id: check
        run: |
          ./gradlew dependencyUpdates -Drevision=release > result.txt
          if grep -q ":\s*\(latest\):" result.txt; then
            echo "status=outdated" >> $GITHUB_OUTPUT
          else
            echo "status=up-to-date" >> $GITHUB_OUTPUT
          fi

      - name: Create badge SVG
        run: |
          STATUS=${{ steps.check.outputs.status }}
          COLOR="brightgreen"
          LABEL="dependencies"
          MESSAGE="up to date"
          if [ "$STATUS" == "outdated" ]; then
            COLOR="red"
            MESSAGE="outdated"
          fi
          echo "<svg xmlns='http://www.w3.org/2000/svg' width='150' height='20'><rect width='70' height='20' fill='#555'/><rect x='70' width='80' height='20' fill='$COLOR'/><text x='10' y='14' fill='#fff'>$LABEL</text><text x='80' y='14' fill='#fff'>$MESSAGE</text></svg>" > dependency-check-badge.svg

      - name: Upload to Gist
        uses: andymckay/gh-gist@v1
        with:
          gist_id: fc45cb1bddace6f645699522179d624f
          file: dependency-check-badge.svg
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
