name: Dependency Check

on:
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday
  workflow_dispatch:

jobs:
  check-dependencies:
    name: Dependency Update Report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Check dependency updates
        id: dependency-check
        run: |
          ./gradlew dependencyUpdates -Drevision=release
          if grep -q "The following dependencies have later versions" build/dependencyUpdates/report.txt; then
            echo "outdated=true" >> $GITHUB_ENV
          else
            echo "outdated=false" >> $GITHUB_ENV
          fi

      - name: Create dynamic badge
        uses: Schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GITHUB_TOKEN }}
          gistID: YOUR_GIST_ID
          filename: dependencies.json
          label: dependencies
          message: ${{ env.outdated == 'true' && 'outdated' || 'up to date' }}
          color: ${{ env.outdated == 'true' && 'red' || 'brightgreen' }}
